### ISSUE TITLE
More instructive parse error messages

### ISSUE THREAD

**Issue by gregerc** [coffeedoc/codo#207]
I just got a 
```
Error: Cannot parse Coffee file file.coffee: unexpected indentation
```
message, and I have no idea what causes it. At least a line number would be extremely helpful :-)

**Comment by inossidabile** [comment]
Use coffee to parse it. I can't imagine a workflow in which you generate docs for a file that has never been executed

**Comment by sschick-prognos** [comment]
I am experiencing this same issue on a file that I have run, repeatedly. I don't get parse errors when I run the code through coffeescript, but codo doesn't seem to handle it well. it seems to me that codo should give a little more information about why it's giving up.

**Comment by justmiles** [comment]
I ran into this as well. Coffee was parsing the file but codo was failing. Turns out the indentation error was for a comment. Coffee won't throw an error because it ignores all comments - but indentation matters for codo.

Nonetheless, I agree. At least provide a line number for where codo failed to parse a comment block.

**Comment by inossidabile** [comment]
Any particular files to test with?
